<a href="https://colab.research.google.com/github/SiddhantMS/PML-Practical-Machine-Learning-/blob/main/Sudeep_Bharghav_PML_logistic_regression_BinaryLogistics_DAY_4%265.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
os.chdir(r"/content/drive/MyDrive/stats")
import numpy as np
import pandas as pd

In [ ]:
import statsmodels.api as sm
from sklearn.model_selection import train_test_split

df = pd.read_excel('StudentData.xlsx')
df = df.drop('Unnamed: 0', axis=1)

# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('Marks', axis=1),df.Marks, test_size=0.2, random_state=20)

# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Marks   R-squared:                       0.722
Model:                            OLS   Adj. R-squared:                  0.682
Method:                 Least Squares   F-statistic:                     17.96
Date:                Mon, 08 Jun 2026   Prob (F-statistic):           1.38e-15
Time:                        03:41:58   Log-Likelihood:                -266.22
No. Observations:                  80   AIC:                             554.4
Df Residuals:                      69   BIC:                             580.6
Df Model:                          10
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
StudyHours        4.9723      2.752      1.807      0.075      -0.518      10.462
PracticeTests     6.1438      3.575      1.719      0.090      -0.987      13.275
RevisionHours    -0.7379      2.690     -0.274      0.785      -6.105       4.629
CoachingHours    -2.0754      3.521     -0.589      0.558      -9.100       4.949
Attendance        1.1862      0.170      6.996      0.000       0.848       1.524
MobileUsage       0.5540      0.473      1.170      0.246      -0.390       1.498
NetflixHours      0.1115      0.402      0.277      0.783      -0.691       0.914
GamingHours       0.1750      0.567      0.309      0.759      -0.956       1.306
SocialMedia       0.1079      0.494      0.219      0.828      -0.877       1.093
SportsHours      -1.2888      0.902     -1.428      0.158      -3.089       0.511
const            37.8871     15.547      2.437      0.017       6.873      68.902
==============================================================================
Omnibus:                        5.697   Durbin-Watson:                   2.195
Prob(Omnibus):                  0.058   Jarque-Bera (JB):                5.022
Skew:                          -0.493   Prob(JB):                       0.0812
Kurtosis:                       3.730   Cond. No.                     1.65e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
df.corr() #we get corelation betn eachother

,StudyHours,PracticeTests,RevisionHours,CoachingHours,Attendance,MobileUsage,NetflixHours,GamingHours,SocialMedia,SportsHours,Marks
StudyHours,1.000000,-0.137275,0.985756,-0.166741,-0.139500,-0.148479,0.039702,-0.119595,-0.116330,0.054158,0.461595
PracticeTests,-0.137275,1.000000,-0.136466,0.982391,0.187605,-0.129208,0.083350,0.098441,0.137525,0.060396,0.455356
RevisionHours,0.985756,-0.136466,1.000000,-0.164784,-0.149062,-0.170147,0.023863,-0.119828,-0.152964,0.079607,0.448704
CoachingHours,-0.166741,0.982391,-0.164784,1.000000,0.230122,-0.115819,0.088085,0.076729,0.100994,0.056112,0.444800
Attendance,-0.139500,0.187605,-0.149062,0.230122,1.000000,-0.090584,0.113714,-0.018171,0.115444,-0.152492,0.430057
MobileUsage,-0.148479,-0.129208,-0.170147,-0.115819,-0.090584,1.000000,-0.086980,0.093279,-0.107880,-0.072796,-0.104220
NetflixHours,0.039702,0.083350,0.023863,0.088085,0.113714,-0.086980,1.000000,-0.106991,0.125457,0.082534,0.140267
GamingHours,-0.119595,0.098441,-0.119828,0.076729,-0.018171,0.093279,-0.106991,1.000000,-0.065969,0.217792,-0.040819
SocialMedia,-0.116330,0.137525,-0.152964,0.100994,0.115444,-0.107880,0.125457,-0.065969,1.000000,-0.212731,0.066168
SportsHours,0.054158,0.060396,0.079607,0.056112,-0.152492,-0.072796,0.082534,0.217792,-0.212731,1.000000,-0.086149
Marks,0.461595,0.455356,0.448704,0.444800,0.430057,-0.104220,0.140267,-0.040819,0.066168,-0.086149,1.000000

In [ ]:
#mULTICOLLINEARITY - OCCURES WHEN THERE ARE CERTURN PAIR OF INPUT FACTORS WHICH HAVE A VERY HIGH VALUE OF COREALATION COEFFICIENT
#BECAUS OF THIS THEY WILL CHANGE/ALTER EFFECT OF THE AOTHER VARIABLES IN THE MODEL

In [ ]:
#IN ORDER TO DETECT MULTYCOLLINERARTY WE CAN CALCULATE VIF-VALUE FOR EACH  COLMN(VARIANCE INFLUATION FACTOR)
#IDELY VIF SHOULD BE LESS THAN 10

In [ ]:
# calculating the vi
from statsmodels.stats.outliers_influence import variance_inflation_factor

x = df.drop('Marks', axis=1)

vif_df = pd.DataFrame()
vif_df['Variable'] = x.columns
vif_df['VIF'] = [
    variance_inflation_factor(x.values, i)
    for i in range(x.shape[1])
]

print("\nVIF VALUES")
print(vif_df.sort_values('VIF', ascending=False))

VIF VALUES
        Variable         VIF
3  CoachingHours  448.533988
1  PracticeTests  444.040942
0     StudyHours  436.685659
2  RevisionHours  407.771297
4     Attendance   60.859442
8    SocialMedia   15.561370
5    MobileUsage    7.811828
9    SportsHours    5.976866
7    GamingHours    5.890728
6   NetflixHours    4.989462

In [ ]:
#conclusion to thes output
#we notice the same factors wehich have a vary high corelation coefficient
#among them are also having high VIF value among ThreadedCompleter

In [ ]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler

x = df.drop('Marks', axis=1)
y=df.Marks
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled = pd.DataFrame(x_scaled, columns=x.columns)

from sklearn.linear_model import LinearRegression
regr1 = LinearRegression()
regr1.fit(x_scaled,y)
regr1.coef_
'''
regr1.coef_
Out[37]:
array([ 5.50805023,  7.25112668,  2.0336992 , -1.39211411,  5.28411473,
        1.09301416,  0.58200739,  0.0777879 ,  0.1418704 , -1.05017386])
'''

'\nregr1.coef_\nOut[37]:\narray([ 5.50805023,  7.25112668,  2.0336992 , -1.39211411,  5.28411473,\n        1.09301416,  0.58200739,  0.0777879 ,  0.1418704 , -1.05017386])\n'

In [ ]:

regr1.intercept_
regr1.feature_names_in_
'''
array(['StudyHours', 'PracticeTests', 'RevisionHours', 'CoachingHours',
       'Attendance', 'MobileUsage', 'NetflixHours', 'GamingHours',
       'SocialMedia', 'SportsHours'], dtype=object)
'''

"\narray(['StudyHours', 'PracticeTests', 'RevisionHours', 'CoachingHours',\n       'Attendance', 'MobileUsage', 'NetflixHours', 'GamingHours',\n       'SocialMedia', 'SportsHours'], dtype=object)\n"

In [ ]:

ridge = Ridge(alpha=10)
ridge.fit(x_scaled,y)
ridge.coef_
'''
array([ 3.82980281,  3.32971683,  3.3198266 ,  2.26051693,  4.63360394,
        0.85365738,  0.59599171,  0.14077832,  0.33850811, -1.0176817 ])
'''

'\narray([ 3.82980281,  3.32971683,  3.3198266 ,  2.26051693,  4.63360394,\n        0.85365738,  0.59599171,  0.14077832,  0.33850811, -1.0176817 ])\n'

In [ ]:
ridge.intercept_
regr1.feature_names_in_

lasso = Lasso(alpha=1)
lasso.fit(x_scaled,y)
lasso.coef_
'''
array([ 6.04772327,  4.72885822,  0.        ,  0.        ,  4.34663537,
        0.        ,  0.        , -0.        ,  0.        , -0.03101151])
'''

'\narray([ 6.04772327,  4.72885822,  0.        ,  0.        ,  4.34663537,\n        0.        ,  0.        , -0.        ,  0.        , -0.03101151])\n'

In [ ]:
lasso.intercept_

np.float64(185.09500000000003)

In [ ]:
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import pandas as pd

df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'diabetes')

df =df[['Glucose','BloodPressure','Age','DietType','Outcome']]

x = df.drop('Outcome', axis=1)
y = df.Outcome

diet_dummy = pd.get_dummies(x.DietType, drop_first=True, prefix='Diet').astype(int)
x = x.drop('DietType', axis=1)
x = pd.concat([x, diet_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

#creting constant
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test,prepend=False)
# creating model here we use function logit
mod3 = sm.Logit(y_train, x_train).fit()
print(mod3.summary())

Optimization terminated successfully.
         Current function value: 0.333614
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  614
Model:                          Logit   Df Residuals:                      608
Method:                           MLE   Df Model:                            5
Date:                Mon, 08 Jun 2026   Pseudo R-squ.:                  0.4848
Time:                        03:41:59   Log-Likelihood:                -204.84
converged:                       True   LL-Null:                       -397.59
Covariance Type:            nonrobust   LLR p-value:                 3.933e-81
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Glucose           0.0368      0.005      7.867      0.000       0.028       0.046
BloodPressure     0.0058      0.007      0.850      0.395      -0.008       0.019
Age               0.0317      0.011      2.908      0.004       0.010       0.053
Diet_2           -3.9276      0.323    -12.142      0.000      -4.562      -3.294
Diet_3           -2.7806      0.344     -8.076      0.000      -3.455      -2.106
const            -4.3877      0.730     -6.012      0.000      -5.818      -2.957
=================================================================================

In [ ]:
# diet_2 analysis: -3.9276
''' in place of diet 1 if we take diet 2  the logos of odds ratio will decrease by -3.9

In [ ]:
y_pred = mod3.predict(x_test)
y_pred

143    0.067186
14     0.455764
504    0.044509
557    0.300460
736    0.074480
         ...
57     0.119158
140    0.195656
713    0.084194
673    0.074613
559    0.075453
Length: 154, dtype: float64

In [ ]:
x_test.iloc[1]

Glucose          166.0
BloodPressure     72.0
Age               51.0
Diet_2             1.0
Diet_3             0.0
const              1.0
Name: 14, dtype: float64

In [ ]:
mydata = pd.DataFrame([[100,75,50,1,0,1],[100,75,51,1,0,1]], columns = x_train.columns)

In [ ]:
mydata

   Glucose  BloodPressure  Age  Diet_2  Diet_3  const
0      100             75   50       1       0      1
1      100             75   51       1       0      1

In [ ]:
mypreds = mod3.predict(mydata)
mypreds

0    0.067899
1    0.069934
dtype: float64

In [ ]:
#logs of odds ratio
LOR_51=np.log(0.069934/1-0.069934)
LOR_51

/tmp/ipykernel_4327/4077720614.py:2: RuntimeWarning: divide by zero encountered in log
  LOR_51=np.log(0.069934/1-0.069934)

np.float64(-inf)

In [ ]:
LOR_50 = np.log(0.067899/1-0.067899)

/tmp/ipykernel_4327/4077751834.py:1: RuntimeWarning: divide by zero encountered in log
  LOR_50 = np.log(0.067899/1-0.067899)

In [ ]:
LOR_51-LOR_50 #0.031716259763
'''# THIS .03171 - INDICATES that when the age inccrease
by one unit the change in the log of odds ratio in faver
 of getting dibites(this is not increasing in probablity it is
                   increase of odds ratio)'''

/tmp/ipykernel_4327/1623750127.py:1: RuntimeWarning: invalid value encountered in scalar subtract
  LOR_51-LOR_50 #0.031716259763

'# THIS .03171 - INDICATES that when the age inccrease\nby one unit the change in the log of odds ratio in faver\n of getting dibites(this is not increasing in probablity it is\n                   increase of odds ratio)'

In [ ]:
# coeff is for inc or dec in favour of logs of odds ratio it is not a probablity

In [ ]:
mydata = pd.DataFrame([[100,75,50,1,0,1],[120,75,51,1,0,1]], columns = x_train.columns)

In [ ]:
mypreds = mod3.predict(mydata)
mypreds

0    0.067899
1    0.135629
dtype: float64

In [ ]:
((np.log(0.135629/(1-0.135629))) - np.log(0.067899/(1-0.067899)))/20

# this output is same as coeff of glocose  so here we can see that
# incerase in one unit of glocose is increse in favour logs ratio

np.float64(0.0383670506578633)

encoding

In [ ]:
df = pd.DataFrame({
    'Education':[
        'Graduate',
        'PG',
        'High School',
        'Graduate',
        'PG'
    ]
})

education_map = {
    'High School':1,
    'Graduate':2,
    'PG':3
}

df['Education_Encoded'] = (
    df['Education']
    .map(education_map)
)

print(df)

     Education  Education_Encoded
0     Graduate                  2
1           PG                  3
2  High School                  1
3     Graduate                  2
4           PG                  3

In [ ]:
# Frequency encoding
df = pd.DataFrame({
    'City':[
        'Mumbai',
        'Mumbai',
        'Mumbai',
        'Delhi',
        'Delhi',
        'Pune'
    ]
})

freq = df.City.value_counts()

df['City_Frequency'] = (df.City.map(freq))

In [ ]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 3.1 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

In [ ]:
# Frequency encoding
df = pd.DataFrame({
    'City':[
        'Mumbai',
        'Mumbai',
        'Mumbai',
        'Delhi',
        'Delhi',
        'Pune'
    ]
})

freq = df.City.value_counts()

df['City_Frequency'] = (df.City.map(freq))

In [ ]:
df = pd.DataFrame({
    'City': [
        'Mumbai',
        'Pune',
        'Delhi',
        'Chennai',
        'Kolkata'
    ]
})


#pip install category_encoders

from category_encoders import BinaryEncoder
encoder = BinaryEncoder(cols=['City'])
df_encoded = encoder.fit_transform(df)
print(df_encoded)

df_encoded = encoder.transform(df)
result = pd.concat([df, df_encoded], axis=1)
print(result)

   City_0  City_1  City_2
0       0       0       1
1       0       1       0
2       0       1       1
3       1       0       0
4       1       0       1
      City  City_0  City_1  City_2
0   Mumbai       0       0       1
1     Pune       0       1       0
2    Delhi       0       1       1
3  Chennai       1       0       0
4  Kolkata       1       0       1

In [ ]:
# why we cant use linear regression insted of logistics regression?
# sigmoid curve
# logs - log of values less than 1 will always be negitive between 0 and 1
# log of any no any base that matter log of 1 log(1) will alway be zero 0
#

In [ ]:
# log of odds ratio
'''
p = f(z) = 1/1+e^-z
log(p/1-p) = z = logs of odds ratio

log(p/1-p) < 0
p/1-p < 1
p<1-p  # this means the pobablity of occuring an event is less than probablity of not occuring

NameError: name 'log' is not defined

dat 5

In [ ]:
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import pandas as pd

df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'diabetes')

df =df[['Glucose','BloodPressure','Age','DietType','Outcome']]

x = df.drop('Outcome', axis=1)
y = df.Outcome

diet_dummy = pd.get_dummies(x.DietType, drop_first=True, prefix='Diet').astype(int)
x = x.drop('DietType', axis=1)
x = pd.concat([x, diet_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

#creting constant
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test,prepend=False)
# creating model here we use function logit
mod3 = sm.Logit(y_train, x_train).fit()
print(mod3.summary())

Optimization terminated successfully.
         Current function value: 0.333614
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  614
Model:                          Logit   Df Residuals:                      608
Method:                           MLE   Df Model:                            5
Date:                Mon, 08 Jun 2026   Pseudo R-squ.:                  0.4848
Time:                        05:21:46   Log-Likelihood:                -204.84
converged:                       True   LL-Null:                       -397.59
Covariance Type:            nonrobust   LLR p-value:                 3.933e-81
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Glucose           0.0368      0.005      7.867      0.000       0.028       0.046
BloodPressure     0.0058      0.007      0.850      0.395      -0.008       0.019
Age               0.0317      0.011      2.908      0.004       0.010       0.053
Diet_2           -3.9276      0.323    -12.142      0.000      -4.562      -3.294
Diet_3           -2.7806      0.344     -8.076      0.000      -3.455      -2.106
const            -4.3877      0.730     -6.012      0.000      -5.818      -2.957
=================================================================================

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_probs = mod3.predict(x_train)
y_pred = []
for ctr in y_probs:
    if ctr >= 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)
print(confusion_matrix(y_train,y_pred))

[[362  37]
 [ 51 164]]

In [ ]:
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.91      0.89       399
           1       0.82      0.76      0.79       215

    accuracy                           0.86       614
   macro avg       0.85      0.84      0.84       614
weighted avg       0.86      0.86      0.86       614

In [ ]:

print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.91      0.89       399
           1       0.82      0.76      0.79       215

    accuracy                           0.86       614
   macro avg       0.85      0.84      0.84       614
weighted avg       0.86      0.86      0.86       614

In [ ]:
(362+164)/(362+164+51+37)

0.8566775244299675

In [ ]:
f1-score is a harmonic mean of precision and recall
1/p + 1/r / 2 = f1-score

out of am , gm , hm
hm is lowest of all of threee
why we use hm we want to show lowest possibility

In [ ]:
when p is high --> bad   for us
when 1-p is low  -> bad
log(1-p) is